INSERT INTO materias VALUES('1',
                            'Núcleo Planck de Artes',
                            'Teatro 9-3',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['15:20'::TIME],
                            30,
                            8,
                            0,
                            1,
                            ARRAY['custo extra'],
                            ARRAY[8, 9, 10, 11]);


INSERT INTO materias VALUES('2',
                            'Núcleo Planck de Artes',
                            'Teatro 6-8',
                            ARRAY[5],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            30,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('3',
                            'Núcleo Planck de Artes',
                            'Bateria A 6-3',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            6,
                            2,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('5',
                            'Núcleo Planck de Artes',
                            'Bateria B 6-3',
                            ARRAY[2],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            6,
                            2,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('5.1',
                            'Núcleo Planck de Artes',
                            'Piano/Teclado A 6-3',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            6,
                            3,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('6',
                            'Núcleo Planck de Artes',
                            'Piano/Teclado B 6-3',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            6,
                            3,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('6.1',
                            'Núcleo Planck de Artes',
                            'Violão A 6-3',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            10,
                            4,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('7',
                            'Núcleo Planck de Artes',
                            'Violão B 6-3',
                            ARRAY[5],
                            ARRAY['16:20'::TIME],
                            ARRAY['18:00'::TIME],
                            10,
                            4,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('7.1',
                            'Núcleo Planck de Artes',
                            'Guitarra/Baixo A 6-3',
                            ARRAY[4],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            10,
                            4,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('9',
                            'Núcleo Planck de Artes',
                            'Guitarra/Baixo B 6-3',
                            ARRAY[5],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            10,
                            4,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('10',
                            'Núcleo Planck de Artes',
                            'Sapateado A 6-3',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['17:30'::TIME],
                            28,
                            8,
                            0,
                            1,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('11',
                            'Núcleo Planck de Artes',
                            'Sapateado B 6-3',
                            ARRAY[5],
                            ARRAY['16:40'::TIME],
                            ARRAY['17:30'::TIME],
                            28,
                            8,
                            0,
                            1,
                            ARRAY['custo extra'],
                            null);


INSERT INTO materias VALUES('13',
                            'Núcleo Planck de Artes',
                            'Street Dance 6-3',
                            ARRAY[4, 6],
                            ARRAY['16:40'::TIME, '16:40'::TIME],
                            ARRAY['18:20'::TIME, '18:20'::TIME],
                            28,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('13.2',
                            'Núcleo Planck de Artes',
                            'Escultura/ Pintura/ Desenho 6-3',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            30,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('13.4',
                            'Núcleo Planck de Artes',
                            'Escultura/ Pintura/ Desenho 6-3',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            30,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('13.2',
                            'Núcleo Planck de Artes',
                            'Escultura/ Pintura/ Desenho 6-3',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            30,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('15.5',
                            'Núcleo Planck de Esportes',
                            'Volei 6-8',
                            ARRAY[3, 5],
                            ARRAY['14:20'::TIME, '15:30'::TIME],
                            ARRAY['15:20'::TIME, '16:30'::TIME],
                            20,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('15.7',
                            'Núcleo Planck de Esportes',
                            'Handball 6-8',
                            ARRAY[5, 6],
                            ARRAY['14:20'::TIME, '14:20'::TIME],
                            ARRAY['15:20'::TIME, '15:20'::TIME],
                            30,
                            12,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('16',
                            'Núcleo Planck de Esportes',
                            'Volei 9-3',
                            ARRAY[2, 4],
                            ARRAY['16:40'::TIME, '14:20'::TIME],
                            ARRAY['17:40'::TIME, '15:20'::TIME],
                            20,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[8, 9, 10, 11]);

INSERT INTO materias VALUES('17',
                            'Núcleo Planck de Esportes',
                            'Futebol 9-3 M',
                            ARRAY[2, 4],
                            ARRAY['15:30'::TIME, '16:40'::TIME],
                            ARRAY['16:30'::TIME, '17:40'::TIME],
                            20,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[8, 9, 10, 11]);

INSERT INTO materias VALUES('19',
                            'Núcleo Planck de Esportes',
                            'Futebol 6-8 F',
                            ARRAY[4, 6],
                            ARRAY['16:40'::TIME, '16:40'::TIME],
                            ARRAY['17:40'::TIME, '17:40'::TIME],
                            20,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5,6, 7]);

INSERT INTO materias VALUES('20',
                            'Núcleo Planck de Esportes',
                            'Futebol 6-8 M',
                            ARRAY[3, 5],
                            ARRAY['17:50'::TIME, '17:50'::TIME],
                            ARRAY['18:50'::TIME, '18:50'::TIME],
                            20,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('21',
                            'Núcleo Planck de Esportes',
                            'Handball 9-3',
                            ARRAY[2, 3],
                            ARRAY['17:50'::TIME, '15:30'::TIME],
                            ARRAY['18:50'::TIME, '16:30'::TIME],
                            30,
                            12,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[8, 9, 10, 11]);

INSERT INTO materias VALUES('22',
                            'Núcleo Planck de Esportes',
                            'Basquete 3x3 6-8',
                            ARRAY[5, 6],
                            ARRAY['16:40'::TIME, '15:30'::TIME],
                            ARRAY['17:40'::TIME, '16:30'::TIME],
                            24,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('22.2',
                            'Núcleo Planck de Esportes',
                            'Basquete 9-3',
                            ARRAY[2, 4],
                            ARRAY['14:20'::TIME, '15:30'::TIME],
                            ARRAY['15:20'::TIME, '16:30'::TIME],
                            20,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[8, 9, 10, 11]);

INSERT INTO materias VALUES('23.1',
                            'Núcleo Planck de Esportes',
                            'Judô 6-8',
                            ARRAY[2, 4],
                            ARRAY['14:20'::TIME, '14:20'::TIME],
                            ARRAY['15:20'::TIME, '15:20'::TIME],
                            24,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('23',
                            'Núcleo Planck de Esportes',
                            'Judô 9-3',
                            ARRAY[2],
                            ARRAY['15:30'::TIME],
                            ARRAY['17:40'::TIME],
                            24,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[ 8, 9, 10, 11]);

INSERT INTO materias VALUES('26',
                            'Núcleo Planck de Esportes',
                            'T. Mesa 6-3',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            16,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5,6,7, 8, 9, 10, 11]);

INSERT INTO materias VALUES('27',
                            'Núcleo Planck de Esportes',
                            'Yoga 6-8',
                            ARRAY[5],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:20'::TIME],
                            24,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5,6,7]);

INSERT INTO materias VALUES('28',
                            'Núcleo Planck de Esportes',
                            'Yoga 9-3',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:20'::TIME],
                            24,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[8, 9, 10, 11]);


INSERT INTO materias VALUES('29',
                            'Núcleo Planck de Esportes',
                            'Xadrez A',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            28,
                            4,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            null);
                            
INSERT INTO materias VALUES('30',
                            'Núcleo Planck de Esportes',
                            'Xadrez B',
                            ARRAY[6],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            28,
                            4,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            null);

INSERT INTO materias VALUES('32',
                            'Núcleo Planck de Tecnologia',
                            'Startup B',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            28,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('32.1',
                            'Núcleo Planck de Tecnologia',
                            'Startup A',
                            ARRAY[4],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            28,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('4',
                            'Núcleo Planck de Tecnologia',
                            'Mídias Soc 6-8',
                            ARRAY[5],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            20,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                             ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('4.5',
                            'Núcleo Planck de Tecnologia',
                            'Mídias Soc 9-3',
                            ARRAY[6],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            20,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                             ARRAY[8, 9, 10, 11]);

INSERT INTO materias VALUES('4.5',
                            'Núcleo Planck de Tecnologia',
                            'Agência Júnior 9-3',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            20,
                            6,
                            0,
                            2,
                            ARRAY['custo extra'],
                             ARRAY[8, 9, 10, 11]);

INSERT INTO materias VALUES('411',
                            'Planck Internacional',
                            'PEC - A2 - EM',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            4,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('412',
                            'Planck Internacional',
                            'PEC - B1 - EM',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            4,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('413',
                            'Planck Internacional',
                            'PEC - B2 - EM',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            4,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('414',
                            'Planck Internacional',
                            'PEC - B2 - EM',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            4,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('415',
                            'Planck Internacional',
                            'PEC - C1 - EM',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            4,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('416',
                            'Planck Internacional',
                            'PEC - C1 - EM',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            4,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('43',
                            'Planck Internacional',
                            'Planck ONU 9-3',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            50,
                            10,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[8, 9,10,11]);

INSERT INTO materias VALUES('44',
                            'Planck Internacional',
                            'Espanhol - A2 - EF',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5,6,7,8]);


INSERT INTO materias VALUES('44',
                            'Planck Internacional',
                            'Espanhol - B2 - EF',
                            ARRAY[2],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[5,6,7,8]);

INSERT INTO materias VALUES('44',
                            'Planck Internacional',
                            'Espanhol - A2 - EM',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('44',
                            'Planck Internacional',
                            'Espanhol - B1 - EM',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY['custo extra'],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('48',
                            'Planck Internacional',
                            'Francês - A1+ - EM',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('49',
                            'Planck Internacional',
                            'Francês - A1+ - EF',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[5,6,7,8]);

INSERT INTO materias VALUES('49.2',
                            'Planck Internacional',
                            'Francês - A1 - EF',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['17:10'::TIME],
                            25,
                            8,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[5,6,7,8]);

INSERT INTO materias VALUES('54.5',
                            'Planck Internacional',
                            'Libras 6-3',
                            ARRAY[5],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            40,
                            10,
                            0,
                            2,
                            ARRAY['custo extra'],
                            null);

INSERT INTO materias VALUES('55',
                            'Programa Planck de Preparação Olímpica',
                            'Física 1-3',
                            ARRAY[4],
                            ARRAY['15:30'::TIME],
                            ARRAY['16:20'::TIME],
                            30,
                            5,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9, 10, 11]);

INSERT INTO materias VALUES('56',
                            'Programa Planck de Preparação Olímpica',
                            'Física 8-9',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['15:10'::TIME],
                            30,
                            5,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[7, 8]);

INSERT INTO materias VALUES('58',
                            'Programa Planck de Preparação Olímpica',
                            'Matemática 6-7 N1',
                            ARRAY[6],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            30,
                            5,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[5, 6]);
INSERT INTO materias VALUES('59',
                            'Programa Planck de Preparação Olímpica',
                            'Matemática 8-9 N2',
                            ARRAY[3],
                            ARRAY['16:40'::TIME],
                            ARRAY['18:20'::TIME],
                            30,
                            5,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[7, 8]);
INSERT INTO materias VALUES('60',
                            'Programa Planck de Preparação Olímpica',
                            'Matemática 1-3 N3',
                            ARRAY[2],
                            ARRAY['15:30'::TIME],
                            ARRAY['18:10'::TIME],
                            30,
                            5,
                            0,
                            3,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('61',
                            'Programa Planck de Preparação Olímpica',
                            'Filosofia 1-3',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['15:10'::TIME],
                            30,
                            5,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[9,10,11]);

INSERT INTO materias VALUES('62',
                            'Programa Planck de Preparação Olímpica',
                            'Química 9-3',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['15:20'::TIME],
                            30,
                            5,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[8,9,10,11]);

INSERT INTO materias VALUES('35',
                            'Programa Planck de Preparação Olímpica',
                            'Astronomia 6-8',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['15:10'::TIME],
                            30,
                            4,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[5, 6, 7]);

INSERT INTO materias VALUES('36',
                            'Programa Planck de Preparação Olímpica',
                            'Astronomia 9-3',
                            ARRAY[3],
                            ARRAY['15:30'::TIME],
                            ARRAY['16:20'::TIME],
                            30,
                            4,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[8,9,10,11]);

INSERT INTO materias VALUES('36',
                            'Programa Planck de Preparação Olímpica',
                            'Programação 6-8',
                            ARRAY[2],
                            ARRAY['14:20'::TIME],
                            ARRAY['15:20'::TIME],
                            15,
                            6,
                            0,
                            1,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[5,6,7]);

INSERT INTO materias VALUES('36',
                            'Programa Planck de Preparação Olímpica',
                            'Programação 9-3',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            15,
                            6,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[8,9,10,11]);

INSERT INTO materias VALUES('36',
                            'Programa Planck de Preparação Olímpica',
                            'Robótica 9-3',
                            ARRAY[3],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            28,
                            4,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[8,9,10,11]);

INSERT INTO materias VALUES('36',
                            'Programa Planck de Preparação Olímpica',
                            'Robótica 6-8',
                            ARRAY[4],
                            ARRAY['14:20'::TIME],
                            ARRAY['16:00'::TIME],
                            28,
                            4,
                            0,
                            2,
                            ARRAY[]::VARCHAR(20)[],
                            ARRAY[5,6,7]);
